openapi: 3.0.0
info:
  title: Todo API
  description: A simple API to manage todos
  version: 1.0.0
servers:
  - url: http://localhost:7686
paths:
  /todos:
    get:
      summary: Get all todos
      responses:
        '200':
          description: A list of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
        '500':
          description: Internal server error
    post:
      summary: Add a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodo'
      responses:
        '201':
          description: The created todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '500':
          description: Internal server error
  /todos/{id}:
    put:
      summary: Update a todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTodo'
      responses:
        '200':
          description: The updated todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found
        '500':
          description: Internal server error
    delete:
      summary: Delete a todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Todo deleted
        '404':
          description: Todo not found
        '500':
          description: Internal server error
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
        text:
          type: string
        completed:
          type: boolean
    NewTodo:
      type: object
      required:
        - text
      properties:
        text:
          type: string
    UpdateTodo:
      type: object
      properties:
        text:
          type: string
        completed:
          type: boolean